### ISSUE TITLE
No such file or directory: './global_checkpoints\\generator_state_dict_0'

### ISSUE THREAD

**Issue by fly125** [inventwithdean/Pix2PixHD#1]
Regarding the two paths of enhanced_checkpointd and global_checkpoints, I don't quite understand what these two paths do![image](https://github.com/user-attachments/assets/87b3b826-dfa5-46b8-828b-8b38f1b32e18)
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\AnimeGANv2Pytorch\diff_fly\Pix2PixHD_inventwithdean\train.py", line 54, in <module>
    load_checkpoint(
  File "D:\BaiduNetdiskDownload\AnimeGANv2Pytorch\diff_fly\Pix2PixHD_inventwithdean\utils.py", line 28, in load_checkpoint
    torch.load(os.path.join(checkpoints_dir, f"generator_state_dict_{epoch}"))
  File "D:\BaiduNetdiskDownload\AnimeGANv2Pytorch\animeganv2_pytorch_venv\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\BaiduNetdiskDownload\AnimeGANv2Pytorch\animeganv2_pytorch_venv\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\BaiduNetdiskDownload\AnimeGANv2Pytorch\animeganv2_pytorch_venv\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './global_checkpoints\\generator_state_dict_0'

**Comment by inventwithdean** [comment]
The path "global_checkpoints" will store the checkpoints of global
generator (Phase 1 training) and "enhanced_checkpoints" will store
checkpoints of the overall setup with local enhancer's checkpoints (Phase 2
training).
But in repo, I didn't include the checkpoints, that's why the both
directories need to be created.
So in your case, firstly make these two directories, then comment out the
load checkpoint function. I will resolve the issue on repo tomorrow.

Thanks for reaching out. Feel free to ask if you have any queries.

Regards,

Abhay
